### PR TITLE
search improvements

### LINKED ISSUE #2: Clicking on a language should search for it

### PR DESCRIPTION
**Pull request by tschuy**
@iankronquist 

This fixes #2 and #1. It makes the language clickable in the search results, and makes language results case insensitive.

### CODE REVIEW

**Comment by tschuy** [comment]
It also orders by newest first.

**Comment by tschuy** [comment]
(Oh, I should mention, I already pushed this to production.)

**Comment by iankronquist** [comment]
There is a bug in this PR. If you click on `Python` to filter Python projects, and then you enter another term in the search box and hit Search you'll get an error that you can't post to '/Python'. Steps to reproduce:
1. Load the page
2. Click 'Python' (or some other language)
3. Enter C++ in the search box & hit enter
4. Get a cruddy page with this error: `Cannot POST /Python`

**Comment by iankronquist** [comment]
Line 5 in [index.hjs](https://github.com/iankronquist/y-cloninator/blob/tschuy/search-improvements/views/index.hjs#L5) probably needs to have an explicit post target.

**Comment by iankronquist** [comment]
Looks good to me. Merging.

**Pull request merged**
